site_name: ZBeyer
highlightjs: true
theme: 
  # name: cinder
  name: bootstrap
  # name: material
custom_dir: 
- 'theme/'

extra_js:
  - 'theme/js/base.js'
  - 'theme/js/jquery-3.3.1.min.js'
  - 'theme/js/bootstrap-3.0.3.min.js'
  - 'theme/js/highlight.pack.js'
 
extra_css:
  - 'theme/css/base.css'
  - 'theme/css/base.min.css'
  - 'theme/css/bootstrap-custom.css'
  - 'theme/css/bootstrap-custom.min.css'
  - 'theme/css/cinder.css'
  - 'theme/css/cinder.min.css'
  - 'theme/css/highlight.css'
  - 'theme/css/highlight.min.css'
  - 'theme/css/highlight.min.css'
  - 'theme/css/xcode.css'
  
# markdown_extensions:
#   - admonition

site_author: Zachary Beyer  
site_description: "Learning MKDocs"
repo_url: "https://github.com/Zbeyer/notes"
copyright: "
<p><a href='https://jquery.com/' target='_blank'>jQuery</a> is provided under the <a href='https://jquery.org/license/' target='_blank'>MIT license</a></p>
<p><a href='https://sourcefoundry.org/cinder/' target='_blank'>Cinder</a> is licensed under the <a href='https://github.com/chrissimpkins/cinder/blob/master/LICENSE.md' target='_blank'>MIT license</a></p>
<p><a href='http://getbootstrap.com/' target='_blank'>Bootstrap</a> is licensed under the <a href='https://github.com/twbs/bootstrap/blob/master/LICENSE' target='_blank'>MIT license</a></p>
<p><a href='https://highlightjs.org/' target='_blank'>highlight.js</a> is reserved under <a href='https://github.com/highlightjs/highlight.js/blob/master/LICENSE' target='_blank'>Copyright (c) 2006, Ivan Sagalaev</a></p>
"